    function [ res ] = TEM( x,y, F )
%  squaring = [];
 
%  range = 0:100;
%  for i = range


    x_bin = [];
    y_bin = [];
    for i = 1:length(x.bin)
        x_bin = [x_bin x.bin(i)-'0'];
        y_bin = [y_bin y.bin(i)-'0'];
    end

    pp_0 = zero_extend([...
            ~(y_bin(8)&x_bin(1)),...
            (y_bin(8)&x_bin(2)),...
            (y_bin(8)&x_bin(3))...
        ],2,11);

    pp_1 = zero_extend([...
            ~(y_bin(7)&x_bin(1)),...
            (y_bin(7)&x_bin(2)),...
            (y_bin(7)&x_bin(3)),...
            (y_bin(7)&x_bin(4)),...
        ],3,11);

    pp_2 = zero_extend([...
            ~(y_bin(6)&x_bin(1)),...
            (y_bin(6)&x_bin(2)),...
            (y_bin(6)&x_bin(3)),...
            (y_bin(6)&x_bin(4)),...
            0
        ],4,11);

    pp_3 = zero_extend([...
            ~(y_bin(5)&x_bin(1)),...
            (y_bin(5)&x_bin(2)),...
            (y_bin(5)&x_bin(3)),...
            (y_bin(5)&x_bin(4)),...
            (y_bin(5)&x_bin(5)),...
            0
        ],5,11);

    pp_4 = zero_extend([...
            ~(y_bin(4)&x_bin(1)),...
            (y_bin(4)&x_bin(2)),...
            (y_bin(4)&x_bin(3)),...
            (y_bin(4)&x_bin(4)),...
            (y_bin(4)&x_bin(5)),...
            (y_bin(4)&x_bin(6)),...
            (y_bin(4)&x_bin(7))...
        ],6,11);

    pp_5 = zero_extend([...
            ~(y_bin(3)&x_bin(1)),...
            (y_bin(3)&x_bin(2)),...
            (y_bin(3)&x_bin(3)),...
            (y_bin(3)&x_bin(4)),...
            (y_bin(3)&x_bin(5)),...
            (y_bin(3)&x_bin(6)),...
            (y_bin(3)&x_bin(7)),...
            (y_bin(3)&x_bin(8))...
        ],7,11);

    pp_6 = zero_extend([...
            ~(y_bin(2)&x_bin(1)),...
            (y_bin(2)&x_bin(2)),...
            (y_bin(2)&x_bin(3)),...
            (y_bin(2)&x_bin(4)),...
            (y_bin(2)&x_bin(5)),...
            (y_bin(2)&x_bin(6)),...
            (y_bin(2)&x_bin(7)),...
            (y_bin(2)&x_bin(8)),...
            0
        ],8,11);


    pp_7 = zero_extend([...
            (y_bin(1)&x_bin(1)),...
            ~(y_bin(1)&x_bin(2)),...
            ~(y_bin(1)&x_bin(3)),...
            ~(y_bin(1)&x_bin(4)),...
            ~(y_bin(1)&x_bin(5)),...
            ~(y_bin(1)&x_bin(6)),...
            ~(y_bin(1)&x_bin(7)),...
            ~(y_bin(1)&x_bin(8)),...
            (y_bin(6)&x_bin(5)),...
            0
        ],9,11);

    pp_8 =[1,0,0,0,0,0,0,1,1,(y_bin(5)&x_bin(6)),0];

    pp = [pp_0;pp_1;pp_2;pp_3;pp_4;pp_5;pp_6;pp_7;pp_8];

    pp = char(pp+'0');

    pp_fi = [];
    for i = 1:9
        temp = fi(0,1,11,0,'OverflowAction', 'Wrap','SumMode', 'SpecifyPrecision', 'SumWordLength', 11+8,'SumFractionLength', 8);
        temp.bin(1:11) = pp(i,:);
        pp_fi = [pp_fi temp];
    end

    temp = sum(pp_fi);
    res = fi(0,1,32,16);
    res.bin(1:11) = temp.bin(1:11);
    res.fimath = F;
%     squaring = [squaring res];
%  end
 end