function compile_hdl_design_squaring_circuit_8bit
% compile_hdl_design_squaring_circuit_8bit compiles HDL design
% Generated by Cosimulation Wizard
[s, r] = system(['vsim < hdlverifier_compile_design.do'],'-echo');
if (s ~= 0)
    error(message('HDLLink:CosimWizard:CompilationError',r));
end

